travis:
  secure:
    BINSTAR_TOKEN: xj7oXgkADsdEjiUq7gIOVqMKarjokYyGpUsN0kDhXF8zHtRlu5CBdrlwwC2VNO09lmYrWzAjChNsUo4D+AVu/n0RezfIK8/+R/skzoaDVxYKKhdRzzLBPS1VmJ5xCJuvrqO5gEcT10gyUF1FjEYVTqQv0XuZC6P2cCaN/x8aUNjThh7iIScxJ6MERxI9MmUM049PC29OOvAkLVODB0Qff4eTewGZegniiaxHlCqyRom3o6K9+aS8UI1SDNku4VhqNjctd1oPVZ6GbCsGTkg8I0PO/jD+5wa27OhGgMEfhvh9BraJXXCPmYJoaECyglpo0jLPRf/fkbq1t/G31AMWHuPBl+k7tuz0VPKolS1NYYTEFTSEM2M1Bowf8shveAM/59BpgEzIdKLajd1WKGCe70NNckts0rF7dvNWP/2tEgsrr3TRY6jSUkiM1QCyPBtxFYJXcvN7TjRa46+wp8zdm2DYdrliK/yV8Z8PJ7J3SdhGT720pMayEpuwsV48UptuWvHyB7g7BmZGMEhqVBANuJC3UvKc23ldRnIZYOX/nOK9Yu3IBuVG3N8VxYXyJWeXYuVv/ZajgbDU731UpK2XGP3FK3ICFU6mRTd5ZbZpceWYkx7e1EnY7lLeR2KEhiS9LQ5qa28umbpYKH+X90BerqO8jAxz6Ww/Y7m7D7QGX90=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
